package Shapes.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Canvas = 0;
  public static final int Circle = 1;
  public static final int Color = 2;
  public static final int ColorReference = 3;
  public static final int Shape = 4;
  public static final int Square = 5;
  public static final int Triangle = 6;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xb0105c5f02f0460fL, 0xa27b731323c47f3fL);
    builder.put(0x6773c3e2c5344c50L, Canvas);
    builder.put(0x6773c3e2c5344c46L, Circle);
    builder.put(0x6773c3e2c5366948L, Color);
    builder.put(0x6773c3e2c53743dfL, ColorReference);
    builder.put(0x6773c3e2c5344c44L, Shape);
    builder.put(0x6773c3e2c5344c4bL, Square);
    builder.put(0x6773c3e2c53924a5L, Triangle);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
